version: '3.8'

# Start: docker-compose up -d
# Shutdown: docker-compose down 
# Remove existing volume: docker volume prune
services:
  mongo:
    image: mongo:6.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: Ff21cHD45eBh1ahEa5HC2Aad5Gbh51DE
      MONGOHOST: "${{RAILWAY_TCP_PROXY_DOMAIN}}"
      MONGOPASSWORD: "${{MONGO_INITDB_ROOT_PASSWORD}}"
      MONGOPORT: "${{RAILWAY_TCP_PROXY_PORT}}"
      MONGOUSER: "${{MONGO_INITDB_ROOT_USERNAME}}"
      MONGO_PRIVATE_URL: "mongodb://${{MONGO_INITDB_ROOT_USERNAME}}:${{MONGO_INITDB_ROOT_PASSWORD}}@${{RAILWAY_PRIVATE_DOMAIN}}:27017"
      MONGO_URL: "mongodb://${{MONGO_INITDB_ROOT_USERNAME}}:${{MONGO_INITDB_ROOT_PASSWORD}}@${{RAILWAY_TCP_PROXY_DOMAIN}}:${{RAILWAY_TCP_PROXY_PORT}}"
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

# Names our volume
volumes:
  mongodb:
